# Generated by Django 5.2.1 on 2025-06-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='person',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.TextField(max_length=10),
        ),
    ]
