# Generated by Django 5.2.1 on 2025-06-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_comment_person_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_on',
            field=models.DateTimeField(),
        ),
    ]
